---
name: CI Pipeline

on:
  push:
    branches: [ci-feature, master]
  pull_request:
    branches: [master]
    types: opened


















    
jobs:
  push-trigger:
    uses: ./.github/workflows/package-release.yml
    with:
      registry: ghcr.io
      smtp_address: smtp.gmail.com
      smtp_port: 587
      ghub_repository: amexei/angular-react-starter
    secrets:
      smtp_username: ${{ secrets.SMTP_USERNAME }}
      smtp_password: ${{ secrets.SMTP_PASSWORD }}
      mail_to: ${{ secrets.MAIL_TO }}
      mail_from: ${{ secrets.MAIL_FROM }}